// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy-0S4RT_aQzX5UrXME4YTQuw3QOcICe0',
    appId: '1:1022961610984:web:cfab483af6e342dcc7995d',
    messagingSenderId: '1022961610984',
    projectId: 'sensor-suhu-49d8b.appspot.com',
    // authDomain: 'suhu-50490.firebaseapp.com',
    databaseURL: 'https://sensor-suhu-49d8b-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-suhu-49d8b.appspot.com',
    measurementId: 'G-5LZB5B6KJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu2x-Crizg-nHs6lY7fAs3lNTdW5CYH_4',
    appId: '1:793458036158:android:de14302a4cd727b3cffdef',
    messagingSenderId: '1022961610984',
    projectId: 'sensor-suhu-49d8b',
    databaseURL: 'https://sensor-suhu-49d8b-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-suhu-49d8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX-TEPgSkHTBw1JNpuMnFKXXhVRIZNB7k',
    appId: '1:1022961610984:ios:c19357e714e5fccdc7995d',
    messagingSenderId: '1022961610984',
    projectId: 'sensor-suhu-49d8b',
    databaseURL: 'https://sensor-suhu-49d8b-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-suhu-49d8b.appspot.com',
    iosClientId:
        '1022961610984-arc9od51chauot42n8maepj0mt7ten9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.temperaturApp',
  );
}
